### ISSUE TITLE
failed to connet to kkmoon 3000

### ISSUE THREAD

**Issue by rUser75** [aquamorta/kkengraver#11]
Hello,
I've a kkmoon 3000 attached to my linux box (centos 8  kernel 4.18.0-193.28.1.el8_2.x86_64 + Python 3.6.8)

the device was discovered by os 

Dec  1 10:03:50 xx kernel: usb 1-1: new full-speed USB device number 7 using xhci_hcd
Dec  1 10:03:51 xx kernel: usb 1-1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.63
Dec  1 10:03:51 xx kernel: usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
Dec  1 10:03:51 xx kernel: usb 1-1: Product: USB2.0-Serial
Dec  1 10:03:51 xx kernel: ch341 1-1:1.0: ch341-uart converter detected
Dec  1 10:03:51 xx kernel: usb 1-1: ch341-uart converter now attached to ttyUSB0

but when I try to connect to the kkmoon

 ./engraver.py -d /dev/ttyUSB0 -vv
[DEBUG]: opening device /dev/ttyUSB0
[DEBUG]: connecting...
[DEBUG]: sending:[10, 0, 4, 0, 255, 0, 4, 0]
[DEBUG]: got acknowledge
[DEBUG]: response read:b''Traceback (most recent call last):
  File "./engraver.py", line 658, in <module>
    engraver.connect()
  File "./engraver.py", line 453, in connect
    self.firmware="%s.%s.%s"%(resp[0],resp[1],resp[2])
IndexError: index out of range

could you help me?

**Comment by aquamorta** [comment]
Hello!

It doen't look good. It seems that you have a new or incompatible firmware, because the device did not react
on receiving the initial byte sequence (10, 0, 4, 0, 255, 0, 4, 0) by sending back its firmware version.
Instead it runs into a timeout.

Maybe kkmoon have changed the init protocol.
I only could improve the software if I would get the new init sequence your device needs.

**Comment by rUser75** [comment]
Thank you.
If you need additional debug info please don't hesitate to ask
